<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Deccansoft-6" ignored="0" name="test 1" tests="6" failures="1" timestamp="23 Jan 2017 08:48:13 GMT" time="0.125" errors="0">
  <testcase name="LoginTest" time="0.014" classname="module1.Testngarray"/>
  <testcase name="LoginTest" time="0.002" classname="module1.Testngarray"/>
  <testcase name="LoginTest" time="0.004" classname="module1.Testngarray"/>
  <testcase name="c" time="0.002" classname="module1.SampleTestng"/>
  <testcase name="f" time="0.014" classname="module1.SampleTestng">
    <failure type="java.lang.AssertionError" message="expected [ttt] but found [aaa]">
      <![CDATA[java.lang.AssertionError: expected [ttt] but found [aaa]
	at module1.SampleTestng.f(SampleTestng.java:48)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- f -->
  <testcase name="a" time="0.002" classname="module1.SampleTestng"/>
</testsuite> <!-- test 1 -->
